### ISSUE TITLE
URL Encoding breaking character search

### ISSUE THREAD

**Issue by Panakamanana** [jbhannah/bestsigs-wow-cacher#1]
I'm a little confused. 

I'll give you an example, you'll see what I mean. When searching for a character with an acute accent for example: Líchwrath (Eu Alonsus) the updater works fine. When then searching for Lupínotuum (Eu Alonsus) it returns an error because its trying to encode the URL as Lup%C3%ADnotuum and of course the url Lup%C3%ADnotuum.png would never return anything.

How come Líchwrath does not get URL Encoded yet Lupínotuum does even though they both use the í character.

**Comment by jbhannah** [comment]
Interesting. There are several characters that have accented letters in their names that seem to be working fine. I'll look into why some might be failing. (Keep in mind that the Best Signatures API has a rate limit of ten requests per character per day.)

**Comment by Panakamanana** [comment]
It's rather unusual unless the request that your sending to best-signatures isn't UTF-8 encoded. But that doesn't explain why some characters work and others do not.

**Comment by Panakamanana** [comment]
Update: Don't know if you have changed anything, but now Líchwrath isn't working either.
